config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  namespace :admin do
    resources :users, :categories
  end

  resources :users, only: [:index, :new, :create, :show]
  resources :ideas

  resources :images, only: [:index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/idea.rb
class Idea < ActiveRecord::Base

  belongs_to :user
  belongs_to :category

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  before_action(:set_category, only: [:show, :edit, :update, :destroy])

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash.notice = "Category '#{@category.name}' Updated!"
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      flash[:errors] = "Please try again!"
      render(:new)
    end
  end

  def destroy
    @category.destroy
    flash.notice = "Category '#{@category.name}' DELETED!!"
    redirect_to(admin_categories_path)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index

  end

  def show
    @admin_user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    @idea = Idea.new(user_id: params[:user_id])
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to @idea.user, notice: "Idea successfully added!"
    else
      flash.notice = "Invalid entry. Please try again."
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)

    flash.notice = "Idea '#{@idea.title}' has been updated!"
    redirect_to @idea
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    flash.notice = "Idea '#{@idea.title}' is gone-zo!"
    redirect_to @idea.user
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :body, :user_id, :category_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.admin?
        redirect_to admin_user_path(@user)
      else
        redirect_to user_path(@user)
      end
    else
      flash.now[:errors] = "Invalid login credentials. Please try again"
      render login_path
    end
  end

  def destroy
    session.clear
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.notice = "Missing Login Information!" #flash[:errors] = "Please try again!"
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>
<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
  <%= link_to category.name, admin_category_path(category) %><br>
<% end %>

<%= link_to "Add New Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/show.html.erb
<h1>Category</h1>
<h2>Category: </h2><%= [:admin, @category.name].last %>
<%= link_to 'Edit', [:edit, :admin, @category] %><br>
<%= link_to "Delete", admin_category_path(@category), method: :delete, data: {confirm: "Really delete the article?"} %>
<%= link_to "<< Back to Categories List", admin_categories_path %><br>

app/views/admin/users/index.html.erb
<h1>Welcome to IdeaBox</h1>

app/views/admin/users/show.html.erb
<h1>Welcome <%= @admin_user.username %></h1>
<%= link_to "Categories", admin_categories_path %>
<%= link_to "Images", images_path %>

app/views/ideas/edit.html.erb
<h1>Edit this idea:</h1>

<%= form_for(@idea) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :body %>
  <%= f.text_field :body %><br>

  <%= f.collection_select(:category_id, Category.all, :id, :name) %><br>

  <%= f.hidden_field :user_id %><br>

  <%= f.submit "Update Idea" %>
<% end %>

app/views/ideas/new.html.erb
<h1>What's your idea?</h1>

<%= form_for(@idea) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  
  <%= f.label :body %>
  <%= f.text_field :body %><br>

  <%= f.collection_select(:category_id, Category.all, :id, :name) %><br>
  
  <%= f.hidden_field :user_id %><br>
  
  <%= f.submit "Create Idea" %>
<% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %>:</h1>

<h3><%= @idea.body %></h3>

<h4>Category: <%= @idea.category.name %></h4>

<%= link_to "<< Back to dashboard", user_path %>

app/views/images/index.html.erb
<h1>Images#index</h1>
<p>Find me in app/views/images/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideabox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash"><%= flash.notice %></p>

<%= yield %>
  <br>
  <br>
  <% if current_user %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>

</body>
</html>

app/views/users/index.html.erb
<h1>Welcome to IdeaBox</h1>
<%= link_to "Create Account", new_user_path %>
<%= link_to "Login", login_path %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.submit "Create Account"%>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

<h2>Here are your ideas:</h2>

<ol>
  <% @user.ideas.each do |idea| %>
    <li><h3><%= link_to "#{idea.title}", idea %></h3><%= button_to "Edit Idea", edit_idea_path(idea), method: :get %><%= button_to "Delete", idea_path(idea), method: :delete %></li>
  <% end %>
</ol>

<%= link_to "Add New Idea", new_idea_path(user_id: @user.id) %>